[global]
thread_count = [1, 10, 20, 30, 40, 50, 60, 70, 80]
numa = [{ policy = "bind", node = 0 }]

[[index]]
hash = "rapid_hash"
name = "arctic"

[[index]]
hash = "rapid_hash"
name = "art"

[[index]]
hash = "rapid_hash"
name = "dash_map"

[[index]]
hash = "rapid_hash"
name = "fb_tree"

[[index]]
hash = "rapid_hash"
name = "wormhole"

[workload]
load = [false]
key = ["u64", "kmer", "ipv4", "snowflake", "url", "email"]
insert_order = ["ordered", "hashed"]
record_count = [100800000]
operation_count = [1000000]
read_proportion = [1.0, 0.95, 0.5]
update_proportion = [0.0, 0.05, 0.5]
insert_proportion = [0.0]
delete_proportion = [0.0]
scan_proportion = [0.0]
read_modify_write_proportion = [0.0]
request_distribution = [{ "zipfian" = 0.99 }]
