[global]
thread_count = [80]
numa = [{ policy = "bind", node = 0 }]

[[index]]
hash = "rapid_hash"
name = "arctic"
reclaim_threshold = 64

[workload]
load = [true]
key = ["u64"]
value = ["box"]
insert_order = ["ordered"]
record_count = [10000000]
operation_count = [100000000]
update_proportion = [0.0]
read_proportion = [0.0]
insert_proportion = [0.5]
delete_proportion = [0.5]
scan_proportion = [0.0]
read_modify_write_proportion = [0.0]
request_distribution = ["uniform"]
