[global]
thread_count = [1, 10, 20, 30, 40, 50, 60, 70, 80]
numa = [{ policy = "bind", node = 0 }]

[[index]]
hash = "rapid_hash"
name = "arctic"

[workload]
load = [false]
key = ["u64", "ipv4", "snowflake", "email", "url"]
value = ["u64"]
insert_order = ["ordered", "hashed"]
record_count = [100800000]
operation_count = [10000000]
update_proportion = [1.0]
read_proportion = [0.0]
insert_proportion = [0.0]
delete_proportion = [0.0]
scan_proportion = [0.0]
read_modify_write_proportion = [0.0]
request_distribution = ["uniform"]
