[global]
thread_count = [60, 80, 100]
numa = [{ policy = "interleave", nodes = [0, 1] }]

[[index]]
hash = "rapid_hash"
name = "arctic"
reclaim_threshold = 256

[workload]
load = [false]
key = ["u64"]
value = ["box"]
insert_order = ["hashed"]
record_count = [100800000]
operation_count = [100000000]
update_proportion = [0.05, 0.5]
read_proportion = [0.95, 0.5]
insert_proportion = [0.0]
delete_proportion = [0.0]
scan_proportion = [0.0]
read_modify_write_proportion = [0.0]
request_distribution = [{ "zipfian" = 0.99 }, { "zipfian" = 1.1 }, { "zipfian" = 1.2 }]
