[global]
thread_count = [60, 80, 100]
numa = [{ policy = "interleave", nodes = [0, 1] }]

[[index]]
hash = "rapid_hash"
name = "arctic"

[workload]
load = [false]
key = ["u64"]
value = ["u64"]
insert_order = ["hashed"]
record_count = [100800000]
operation_count = [100000000]
update_proportion = [0.05]
read_proportion = [0.95]
insert_proportion = [0.0]
delete_proportion = [0.0]
scan_proportion = [0.0]
read_modify_write_proportion = [0.0]
request_distribution = [{ "zipfian" = 0.99 }, { "zipfian" = 1.05 }, { "zipfian" = 1.1 }]
