[global]
thread_count = [40, 80, 120]
numa = [{ policy = "bind", node = 0 }]

[[index]]
hash = "rapid_hash"
name = "arctic"
reclaim_threshold = 64

[[index]]
hash = "rapid_hash"
name = "arctic"
reclaim_threshold = 128

[[index]]
hash = "rapid_hash"
name = "arctic"
reclaim_threshold = 256

[[index]]
hash = "rapid_hash"
name = "arctic"
reclaim_threshold = 512

[[index]]
hash = "rapid_hash"
name = "arctic"
reclaim_threshold = 1024

[workload]
load = [false]
key = ["u64"]
value = ["box"]
insert_order = ["hashed"]
record_count = [100080000]
operation_count = [100000000]
update_proportion = [0.5]
read_proportion = [0.0]
insert_proportion = [0.0]
delete_proportion = [0.5]
scan_proportion = [0.0]
read_modify_write_proportion = [0.0]
request_distribution = ["uniform"]
