[global]
thread_count = [80]
numa = [{ policy = "bind", node = 0 }]

[[index]]
hash = "rapid_hash"
name = "arctic"

[[index]]
hash = "rapid_hash"
name = "art"

[[index]]
hash = "rapid_hash"
name = "fb_tree"

[[index]]
hash = "rapid_hash"
name = "wormhole"

[workload]
load = [false]
key = [{ "ts" = 1 }, { "ts" = 10 }, { "ts" = 100 }, { "ts" = 1000 }, { "ts" = 10000 }, { "ts" = 100000 }, { "ts" = 1000000 }]
value = ["u64"]
insert_order = ["ordered"]
record_count = [100800000]
operation_count = [1000000]
update_proportion = [0.0]
read_proportion = [0.0]
insert_proportion = [0.05]
delete_proportion = [0.0]
scan_proportion = [0.95]
read_modify_write_proportion = [0.0]
request_distribution = ["uniform"]
