[global]
thread_count = [1, 20, 40, 60, 80, 100, 120, 140, 160]
numa = [{ policy = "interleave", nodes = [0, 1] }]

[[index]]
hash = "rapid_hash"
name = "arctic"

[[index]]
hash = "rapid_hash"
name = "art"

# [[index]]
# hash = "rapid_hash"
# name = "fb_tree"

[[index]]
hash = "rapid_hash"
name = "wormhole"

[workload]
load = [false]
key = ["u64", "ipv4", "snowflake", "url", "email"]
value = ["u64"]
insert_order = ["ordered", "hashed"]
record_count = [100800000]
operation_count = [100000000]
read_proportion = [0.0]
update_proportion = [0.0]
insert_proportion = [0.05]
delete_proportion = [0.0]
scan_proportion = [0.95]
max_scan_length = [100]
read_modify_write_proportion = [0.0]
request_distribution = [{ "zipfian" = 0.99 }]
