[global]
thread_count = [1, 10, 20, 30, 40, 50, 60, 70, 80]
numa = [{ policy = "interleave", nodes = [0, 1] }]

[[index]]
name = "arctic"

[[index]]
name = "art"

[[index]]
name = "concurrent_map"

[[index]]
name = "congee"

[[index]]
name = "contrie"

[[index]]
name = "crossbeam_skiplist"

[[index]]
name = "dash_map"

[[index]]
name = "fb_tree"

[[index]]
name = "hot"

[[index]]
name = "masstree"

[[index]]
name = "papaya"

[[index]]
name = "scc_hash_index"

[[index]]
name = "scc_hash_map"

[[index]]
name = "scc_tree_index"

[[index]]
name = "wormhole"

[workload]
load = [false]
key = ["ipv4", "u64", "snowflake", "uuid_v4", "email", "url"]
value = ["u64"]
insert_order = ["ordered", "hashed"]
record_count = [10000, 100000, 1000000, 10000000, 100000000]
operation_count = [100000000]
read_proportion = [0.95]
update_proportion = [0.0]
insert_proportion = [0.05]
delete_proportion = [0.0]
scan_proportion = [0.0]
read_modify_write_proportion = [0.0]
request_distribution = [{ "latest" = 0.0 }, { "latest" = 0.99 }]
